-- EXEMPLOS AULA 7 - FUNCOES
-- FUNCOES NUMERICAS

SELECT 
    LAST_NAME,
    SALARY,
    ROUND(SALARY,4) FUNC_ROUND,
    MOD(SALARY,3) FUNC_MOD,
    TRUNC(SALARY,0) FUNC_TRUNC,
    ABS(SALARY * (-1)) FUNC_ABS,
    SQRT(SALARY) UNC_SQRT,
    FLOOR(SALARY) FUNC_FLOOR,
    CEIL(SALARY) FUNC_CEIL
        FROM EMPLOYEES;

-- COMPARACAO DE FUNCOES QUE AGEM SOBRE VALORES COM PONTO FLUTUANTE (CASAS DECIMAIS)
        
SELECT 
    LAST_NAME,
    SALARY,
    SQRT(SALARY) UNC_SQRT,
    ROUND(SQRT(SALARY),2) FUNC_ROUND,
    TRUNC(SQRT(SALARY),2) FUNC_TRUNC,
    FLOOR(SQRT(SALARY)) FUNC_FLOOR,
    CEIL(SQRT(SALARY)) FUNC_CEIL
        FROM EMPLOYEES;
        
-- FUNCOES DE CARACTER

SELECT
    FIRST_NAME,
    LOWER(FIRST_NAME) FUNC_LOWER,
    UPPER(FIRST_NAME) FUNC_UPPER,
    INITCAP(FIRST_NAME) FUNC_INITCAP
        FROM EMPLOYEES;

-- CONCAT SUBST E LENGHT

SELECT
    FIRST_NAME,
    CONCAT(FIRST_NAME, LAST_NAME) FUNC_CONCAT1,
    CONCAT(FIRST_NAME, '_ABC') FUNC_CONCAT2,
    SUBSTR(FIRST_NAME,1,3) FUNC_SUBSRTR1,
    SUBSTR(FIRST_NAME,3) FUNC_SUBSTR2,
    LENGTH(FIRST_NAME) FUNC_LENGTH
        FROM EMPLOYEES;
        
-- INSTR

SELECT 
    FIRST_NAME,
    INSTR(FIRST_NAME, 'A') FUNC_INSTR1,
    INSTR(FIRST_NAME, 'a', 3) FUNC_INSTR2,
    INSTR(FIRST_NAME, 'e', 3, 2) FUNC_INSTR3
        FROM EMPLOYEES;
        
-- RPAD /LPAD

SELECT
    FIRST_NAME,
    RPAD(FIRST_NAME, 20) FUNC_RPAD1,
    RPAD(FIRST_NAME, 20, '.') FUNC_RPAD2,
    LPAD(FIRST_NAME, 20, '*') FUNC_LPAD
        FROM EMPLOYEES;
        
-- LTRIM, RTRIM E TRIM

SELECT
    FIRST_NAME,
    LTRIM(FIRST_NAME) FUNC_LTRIM1,
    LTRIM(FIRST_NAME,'A') FUNC_LTRIM2,
    RTRIM(FIRST_NAME) FUNC_RTRIM1,
    RTRIM(FIRST_NAME, 'a') FUNC_RTRIM2,
    TRIM(FIRST_NAME) FUNC_TRIM1,
    TRIM('A' FROM FIRST_NAME) FUNC_TRIM2
        FROM EMPLOYEES;
        
-- REPLACE

SELECT
    FIRST_NAME,
    REPLACE(FIRST_NAME, 'e', '*') FUNC_REPLACE
        FROM EMPLOYEES;
    
-- FUNCOES DE CONVERSAO

--TO_CHAR

SELECT
    1234 ENTRADA,
    TO_CHAR(1234,'$99999') TO_CHAR_1,
    TO_CHAR(1234,'999,999') TO_CHAR_2,
    TO_CHAR(1234,'9999.99') TO_CHAR_3,
    TO_CHAR(1234,'099999') TO_CHAR_4,
    TO_CHAR(1234,'99999') TO_CHAR_5,
    TO_CHAR(1234,'B099999') TO_CHAR_6,
    TO_CHAR(1234,'c99999') TO_CHAR_7
        FROM DUAL;

-- TO_CHAR -> DATAS

SELECT
    CURRENT_DATE ENTRADA,
    TO_CHAR(CURRENT_DATE, 'DD') DD,
    TO_CHAR(CURRENT_DATE, 'DY') DY,
    TO_CHAR(CURRENT_DATE, 'DAY') DAY,
    TO_CHAR(CURRENT_DATE, 'DDSP') DDSP,
    TO_CHAR(CURRENT_DATE, 'MM') MM,
    TO_CHAR(CURRENT_DATE, 'MON') MMON,
    TO_CHAR(CURRENT_DATE, 'MONTH') MMONTH,
    TO_CHAR(CURRENT_DATE, 'YY') YY,
    TO_CHAR(CURRENT_DATE, 'YYYY') YYYY,
    TO_CHAR(CURRENT_DATE, 'RRRR') RRRR,
    TO_CHAR(CURRENT_DATE, 'HH:MI:SS') HHMISS,
    TO_CHAR(CURRENT_DATE, 'HH24') HH24
        FROM DUAL;
    
-- LEMBRETE -  ALTERACAO DA FORMATACAO DE DATA DA SESSAO

ALTER SESSION
    SET NLS_DATE_FORMAT = 'DD/MM/YYYY';
    
-- LEMBRETE -  ALTERACAO DA FORMATACAO DE LINGUAGEM DA SESSAO

ALTER SESSION
    SET NLS_DATE_LANGUAGE = 'PORTUGUESE';

-- TO NUMBER

SELECT
    '1234' ENTRADA,
    TO_NUMBER('1234') + 1234 TO_NUMBER_1
        FROM DUAL;

-- TO DATE

SELECT
    '17/10/1994' ENTRADA,
    TO_DATE('17/10/1994', 'DD/MM/RR') TO_DATE_1
        FROM DUAL;

-- FUNCOES DE DATA

SELECT
    CURRENT_DATE ENTRADA,
    SYSDATE ENTRADA_1,
    SYSTIMESTAMP ENTRADA_2,
    CURRENT_TIMESTAMP ENTRADA_3,
    ADD_MONTHS(CURRENT_DATE, 2) ADD_MON_1,
    ADD_MONTHS(CURRENT_DATE, -2) ADD_MON_2
        FROM DUAL;

-- MONTHS_BETWEEN
    
SELECT
    MONTHS_BETWEEN(CURRENT_DATE, '01/01/2018') MONTHS1,
    MONTHS_BETWEEN('05/05/2018', '01/01/2018') MONTHS2,
    MONTHS_BETWEEN('05/05/2017', '01/01/2018') MONTHS3
        FROM DUAL;
    



















        
        
        