-- EXERCICIOS - AULA 7

SELECT * FROM EMPLOYEES;

-- EX 1

SELECT
    FIRST_NAME,
    UPPER(FIRST_NAME) NOME_MAIUSCULO
        FROM EMPLOYEES;
        
-- EX 2

SELECT
    FIRST_NAME,
    HIRE_DATE,
    CURRENT_DATE,
    FLOOR((MONTHS_BETWEEN(CURRENT_DATE, HIRE_DATE)) / 12) TEMPO_TRABALHADO
        FROM EMPLOYEES;

-- EX 3

SELECT
    FIRST_NAME
        FROM EMPLOYEES
        WHERE INSTR(FIRST_NAME, 'M') = 1;
        
SELECT 
    COUNT (*) 
        FROM EMPLOYEES 
        WHERE SUBSTR(FIRST_NAME, 1, 1) = 'M';
    
-- EX 4 

SELECT
    FIRST_NAME,
    SALARY,
    CEIL(SALARY) ARREDONDADO
        FROM EMPLOYEES;
        
    
    
    
    